name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache dependencies
        id: cache-result
        uses: Swatinem/rust-cache@v1
      - name: Install Cargo-vcpkg
        if: steps.cache-result.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-vcpkg
      - name: Build vcpkg dependencies
        if: steps.cache-result.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: vcpkg
          args: build
      - uses: actions-rs/cargo@v1
        with:
          command: check
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
  clippy:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true
      - name: Cache dependencies
        id: cache-result
        uses: Swatinem/rust-cache@v1
      - name: Install Cargo-vcpkg
        if: steps.cache-result.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-vcpkg
      - name: Build vcpkg dependencies
        if: steps.cache-result.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: vcpkg
          args: build
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache dependencies
        id: cache-result
        uses: Swatinem/rust-cache@v1
      - name: Install Cargo-vcpkg
        if: steps.cache-result.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-vcpkg
      - name: Build vcpkg dependencies
        if: steps.cache-result.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: vcpkg
          args: build
      - uses: actions-rs/cargo@v1
        with:
          command: test
